// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryBlazorApp.Repository.Data;

#nullable disable

namespace SalaryBlazorApp.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250705145240_main_menu_feature")]
    partial class main_menu_feature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalaryBlazorApp.Repository.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            Order = 1,
                            ParentId = 0,
                            Title = "Liquidaciones",
                            Url = "/liquidaciones"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Order = 2,
                            ParentId = 0,
                            Title = "Informes",
                            Url = "/informes"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Order = 3,
                            ParentId = 0,
                            Title = "Archivos",
                            Url = "/archivos"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Order = 4,
                            ParentId = 0,
                            Title = "Varios",
                            Url = "/varios"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = false,
                            Order = 5,
                            ParentId = 0,
                            Title = "Consultas",
                            Url = "/consultas"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = false,
                            Order = 6,
                            ParentId = 0,
                            Title = "Ejecutar",
                            Url = "/ejecutar"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = false,
                            Order = 7,
                            ParentId = 0,
                            Title = "Salir",
                            Url = "/salir"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = false,
                            Order = 1,
                            ParentId = 4,
                            Title = "Datos de la liquidación",
                            Url = "/datos_liquidacion"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = false,
                            Order = 2,
                            ParentId = 4,
                            Title = "Datos de la empresa",
                            Url = "/datos_empresa"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = false,
                            Order = 3,
                            ParentId = 4,
                            Title = "Parámetros",
                            Url = "/parametros"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = false,
                            Order = 4,
                            ParentId = 4,
                            Title = "Formatos de formularios",
                            Url = "/formatos_formularios"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = false,
                            Order = 5,
                            ParentId = 4,
                            Title = "Importación",
                            Url = "/importacion"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = false,
                            Order = 6,
                            ParentId = 4,
                            Title = "Eliminación histórico",
                            Url = "/eliminacion_historico"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = false,
                            Order = 7,
                            ParentId = 4,
                            Title = "Impresoras",
                            Url = "/impresoras"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = false,
                            Order = 1,
                            ParentId = 12,
                            Title = "Formatos de archivos",
                            Url = "/formatos_archivos"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = false,
                            Order = 2,
                            ParentId = 12,
                            Title = "Listado de formatos",
                            Url = "/listado_formatos"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = false,
                            Order = 3,
                            ParentId = 12,
                            Title = "Definición de sinónimos",
                            Url = "/definicion_sinonimos"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = false,
                            Order = 4,
                            ParentId = 12,
                            Title = "Listado de sinónimos",
                            Url = "/listado_sinonimos"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = false,
                            Order = 5,
                            ParentId = 12,
                            Title = "Importación de archivos",
                            Url = "/importacion_archivos"
                        });
                });

            modelBuilder.Entity("SalaryBlazorApp.Repository.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
