// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryBlazorApp.Repository.Data;

#nullable disable

namespace SalaryBlazorApp.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250707162458_EmployeeTableCreated")]
    partial class EmployeeTableCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalaryBlazorApp.Repository.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoCasada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaracterServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoBaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Discapacidad")
                        .HasColumnType("bit");

                    b.Property<string>("DomicilioCalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioDepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioExplotacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioNro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioPiso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinciaEmision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("SalaryBlazorApp.Repository.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            Order = 1,
                            Title = "Liquidaciones"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Order = 2,
                            Title = "Informes"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Order = 3,
                            Title = "Archivos"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Order = 4,
                            Title = "Varios"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = false,
                            Order = 5,
                            Title = "Consultas"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = false,
                            Order = 6,
                            Title = "Ejecutar"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = false,
                            Order = 7,
                            Title = "Salir",
                            Url = "/salir"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = false,
                            Order = 1,
                            ParentId = 4,
                            Title = "Datos de la liquidación",
                            Url = "/datos_liquidacion"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = false,
                            Order = 2,
                            ParentId = 4,
                            Title = "Datos de la empresa",
                            Url = "/datos_empresa"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = false,
                            Order = 3,
                            ParentId = 4,
                            Title = "Parámetros",
                            Url = "/parametros"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = false,
                            Order = 4,
                            ParentId = 4,
                            Title = "Formatos de formularios",
                            Url = "/formatos_formularios"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = false,
                            Order = 5,
                            ParentId = 4,
                            Title = "Importación"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = false,
                            Order = 6,
                            ParentId = 4,
                            Title = "Eliminación histórico",
                            Url = "/eliminacion_historico"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = false,
                            Order = 7,
                            ParentId = 4,
                            Title = "Impresoras",
                            Url = "/impresoras"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = false,
                            Order = 1,
                            ParentId = 12,
                            Title = "Formatos de archivos",
                            Url = "/formatos_archivos"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = false,
                            Order = 2,
                            ParentId = 12,
                            Title = "Listado de formatos",
                            Url = "/listado_formatos"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = false,
                            Order = 3,
                            ParentId = 12,
                            Title = "Definición de sinónimos",
                            Url = "/definicion_sinonimos"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = false,
                            Order = 4,
                            ParentId = 12,
                            Title = "Listado de sinónimos",
                            Url = "/listado_sinonimos"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = false,
                            Order = 5,
                            ParentId = 12,
                            Title = "Importación de archivos",
                            Url = "/importacion_archivos"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = false,
                            Order = 1,
                            ParentId = 3,
                            Title = "Legajos"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = false,
                            Order = 2,
                            ParentId = 3,
                            Title = "Datos para SICOSS"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = false,
                            Order = 3,
                            ParentId = 3,
                            Title = "Conceptos"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = false,
                            Order = 4,
                            ParentId = 3,
                            Title = "Grupos de conceptos",
                            Url = "/grupos_conceptos"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = false,
                            Order = 5,
                            ParentId = 3,
                            Title = "Reparticiones",
                            Url = "/reparticiones"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = false,
                            Order = 6,
                            ParentId = 3,
                            Title = "Convenios"
                        },
                        new
                        {
                            Id = 26,
                            IsActive = false,
                            Order = 7,
                            ParentId = 3,
                            Title = "Centros de costos",
                            Url = "/centro_costos"
                        },
                        new
                        {
                            Id = 27,
                            IsActive = false,
                            Order = 8,
                            ParentId = 3,
                            Title = "Sectores",
                            Url = "/sectores"
                        },
                        new
                        {
                            Id = 28,
                            IsActive = false,
                            Order = 9,
                            ParentId = 3,
                            Title = "Referencias contables",
                            Url = "/referencias_contables"
                        },
                        new
                        {
                            Id = 29,
                            IsActive = false,
                            Order = 10,
                            ParentId = 3,
                            Title = "Impuesto a las ganacias"
                        },
                        new
                        {
                            Id = 30,
                            IsActive = false,
                            Order = 11,
                            ParentId = 3,
                            Title = "Billetes y monedas",
                            Url = "/billetes_monedas"
                        },
                        new
                        {
                            Id = 31,
                            IsActive = false,
                            Order = 1,
                            ParentId = 20,
                            Title = "Datos operativos",
                            Url = "/datos_operativos"
                        },
                        new
                        {
                            Id = 32,
                            IsActive = false,
                            Order = 2,
                            ParentId = 20,
                            Title = "Datos generales",
                            Url = "/datos_generales"
                        },
                        new
                        {
                            Id = 33,
                            IsActive = false,
                            Order = 3,
                            ParentId = 20,
                            Title = "Datos para SICOSS",
                            Url = "/datos_sicoss"
                        },
                        new
                        {
                            Id = 34,
                            IsActive = false,
                            Order = 4,
                            ParentId = 20,
                            Title = "Acumulados mensuales",
                            Url = "/acum_mensuales"
                        },
                        new
                        {
                            Id = 35,
                            IsActive = false,
                            Order = 5,
                            ParentId = 20,
                            Title = "Acumulados anuales",
                            Url = "/acum_anuales"
                        },
                        new
                        {
                            Id = 36,
                            IsActive = false,
                            Order = 6,
                            ParentId = 20,
                            Title = "Imp. a las ganacias"
                        },
                        new
                        {
                            Id = 37,
                            IsActive = false,
                            Order = 7,
                            ParentId = 20,
                            Title = "Familiares",
                            Url = "/familiares"
                        },
                        new
                        {
                            Id = 38,
                            IsActive = false,
                            Order = 8,
                            ParentId = 20,
                            Title = "Reparticiones"
                        });
                });

            modelBuilder.Entity("SalaryBlazorApp.Repository.Models.MenuItem", b =>
                {
                    b.HasOne("SalaryBlazorApp.Repository.Models.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SalaryBlazorApp.Repository.Models.MenuItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
